name: NitroSpawners
main: centralworks.spawners.Main
author: <Leonardo/>
version: 1.2.0
description: A advanced plug-in of Spawners system
depend: [HolographicDisplays, NBTAPI, PlaceholderAPI]
softdepend: [dynmap]